name: SonarQube Scan
description: Generate Sonar properties and run SonarQube scan

inputs:
  project-key:
    description: Sonar Project Key
    required: true

  project-name:
    description: Sonar Project Name
    required: true

  sources:
    description: Source directory
    required: false
    default: "."

  tests:
    description: Test directory
    required: false
    default: "tests"

  coverage-report:
    description: Coverage report
    required: false
    default: "coverage.xml"

  test-report:
    description: Test report
    required: false
    default: "test-results.xml"

  exclusions:
    description: Sonar exclusions
    required: false
    default: ""

  sonar-token:
    description: Sonar Token
    required: true

runs:
  using: composite

  steps:
    - name: Generate sonar-project.properties
      shell: bash
      run: |
        cp "${{ github.action_path }}/sonar-project.properties.template" sonar-project.properties

        sed -i "s|@PROJECT_KEY@|${{ inputs.project-key }}|g" sonar-project.properties
        sed -i "s|@PROJECT_NAME@|${{ inputs.project-name }}|g" sonar-project.properties
        sed -i "s|@SOURCES@|${{ inputs.sources }}|g" sonar-project.properties
        sed -i "s|@TESTS@|${{ inputs.tests }}|g" sonar-project.properties
        sed -i "s|@COVERAGE_REPORT@|${{ inputs.coverage-report }}|g" sonar-project.properties
        sed -i "s|@TEST_REPORT@|${{ inputs.test-report }}|g" sonar-project.properties
        sed -i "s|@EXCLUSIONS@|${{ inputs.exclusions }}|g" sonar-project.properties

    - name: Run SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        args: >
          -Dsonar.qualitygate.wait=true