name: python-ci-pipeline

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version
        required: false
        type: string
        default: "3.12"
      java-version:
        description: Java version
        required: false
        type: string
        default: "17"

jobs:
  ci:
    name: Python CI
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        uses: irajatpandey/platform-workflows/.github/actions/common-setup@master
        with:
          python-version: ${{ inputs.python-version }}
          java-version: ${{ inputs.java-version }}
          setup-python: "true"
          setup-java: "true"
          install-gitleaks: "true"
     