name: python-ci-pipeline

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version
        required: false
        type: string
        default: "3.12"

      exclusions:
        description: Sonar exclusions
        required: false
        type: string
        default: ""

      java-version:
        description: Java version
        required: false
        type: string
        default: "17"

    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  python-ci:
    name: Python CI
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: irajatpandey/platform-workflows/.github/actions/steps/setup-python@master
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup Java
        uses: irajatpandey/platform-workflows/.github/actions/steps/setup-java@master
        with:
          java-version: ${{ inputs.java-version }}

      - name: Run Gitleaks
        uses: irajatpandey/platform-workflows/.github/actions/steps/run-gitleaks@master

      - name: Upload HTML Report
        uses: irajatpandey/platform-workflows/.github/actions/steps/upload-artifact@master

      - name: Run Unit Tests and Code Coverage
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

          pytest \
            --junitxml=test-results.xml \
            --cov=. \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/

      - name: SAST / SonarQube Analysis
        uses: irajatpandey/platform-workflows/.github/actions/steps/sonarqube@master
        with:
          project-key: irajatpandey_platform-workflows
          project-name: Platform Workflows
          exclusions: ${{ inputs.exclusions }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}